# Generated by Django 6.0 on 2025-12-18 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_episodes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=10)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('watchlist', 'Watchlist')], default='watchlist', max_length=15)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review', models.TextField(blank=True, null=True)),
                ('ai_review_summary', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='core_media_status_7b9bd7_idx'), models.Index(fields=['platform'], name='core_media_platfor_e533bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeasonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_watched', models.PositiveIntegerField(default=0)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_progress', to='core.season')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv_details', to='core.media')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='tv_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.tvshowdetails'),
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='core.media')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_medias', to='core.genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_genres', to='core.media')),
            ],
            options={
                'unique_together': {('media', 'genre')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('tv_details', 'season_number')},
        ),
    ]
