# Generated by Django 6.0 on 2025-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(related_name='media', through='core.MediaGenre', to='core.genre'),
        ),
    ]
