# Generated by Django 6.0 on 2025-12-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='genres',
        ),
    ]
